POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Canavaggio",
    "surname": "Lorenzo",
    "birthdate": "2018-01-01",
    "email": "lorenzo.canavaggio3@laposte.net",
    "password": "porunga"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"lorenzo.canavaggio3@laposte.net",
    "password":"porunga"
}

###
### Everything beyond this point need JWT Token
###

GET http://localhost:3000/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjEyMTk4OTYsImV4cCI6MTU2MTIyMzQ5Nn0.f6JhRqnTj2-BdtAeqv-ExCVQL6v7aONGfpwLZgxOcGo

###

POST http://localhost:3000/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjEyMTk4OTYsImV4cCI6MTU2MTIyMzQ5Nn0.f6JhRqnTj2-BdtAeqv-ExCVQL6v7aONGfpwLZgxOcGo

###

GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjEyOTM5MDMsImV4cCI6MTU2MTI5NzUwM30.1AB4Mz4E-b0F6gH0dlIltXoR2kADP-8_nH2RV3rCt7o

###

GET http://localhost:3000/api/v1/users?_id=5d0e2fc7cb42b200bcf58b68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjEyODkzNzksImV4cCI6MTU2MTI5Mjk3OX0.YwiLct9eUfqJ7Yp4UMiYaE2K3uS8nNRlX5mESRixVss

###

GET http://localhost:3000/api/v1/users?name=Canavaggio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjEyODkzNzksImV4cCI6MTU2MTI5Mjk3OX0.YwiLct9eUfqJ7Yp4UMiYaE2K3uS8nNRlX5mESRixVss

###

DELETE http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjEyOTM5MDMsImV4cCI6MTU2MTI5NzUwM30.1AB4Mz4E-b0F6gH0dlIltXoR2kADP-8_nH2RV3rCt7o

{
    "id":"5d0f74710ed71f02364a0111"
}

###
PUT http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjEyOTM5MDMsImV4cCI6MTU2MTI5NzUwM30.1AB4Mz4E-b0F6gH0dlIltXoR2kADP-8_nH2RV3rCt7o

{
    "id":"5d0f74720ed71f02364a0112",
    "name": "Canavaggio",
    "surname": "Henri",
    "birthdate": "2018-01-01"
}

###
POST http://localhost:3000/api/v1/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjE0NjkwNzUsImV4cCI6MTU2MTQ3MjY3NX0.DSwJXz6EriTi7YKXKiYDBGyqtLeq_w83NGiyYuLsnmg

{
    "title": "SDREEEE",
    "description": "SDREEEE",
    "content": "SDREEEE",
    "date": "2018-01-01",
    "timetoread": 15,
    "profilepictureurl": "SDREEEE",
    "mainimage": "SDREEEE",
    "score": 40,
    "type": {"name":"type1","description":"type1 description"},
    "tags": [{"name":"tag1","description":"tag1 description"},{"name":"tag2","description":"tag2 description"}]
}